### ISSUE TITLE
How to publish an artifact?

### ISSUE THREAD

**Issue by iMonZ** [samuelmeuli/action-snapcraft#28]
Hey,

I have this workflow:
```
- name: Snapcraft build
      if: matrix.platform == 'ubuntu-latest'
      uses: snapcore/action-build@v1
      id: snapcraft
    - name: Snapcraft artifact upload
      if: matrix.platform == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: Linux Snapcraft
        path: ${{ steps.snapcraft.outputs.snap }}
```

How can I convert this workflow into samuelmeuli?
I mean how can I upload an artifact with this fork?

**Comment by casperdcl** [comment]
```yaml
    ...
    steps:
    ...
    - name: Snap install
      uses: samuelmeuli/action-snapcraft@v1
      with:
        use_lxd: true
    - name: Snap build
      run: "sg lxd -c 'snapcraft --use-lxd'"
    - name: Snap upload
      id: snapcraft
      run: |
        snapcraft upload *.snap --release edge
        echo ::set-output name=snap::$(ls *.snap)
    - name: Snapcraft artifact upload
      uses: actions/upload-artifact@v2
      ...
      with:
        ...
        path: ${{ steps.snapcraft.outputs.snap }}
```
